[tool.poetry]
name = "downloadservice"
version = "0.1.0"
description = ""
authors = ["Volodymyr Savchenko <contact@volodymyrsavchenko.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask-oidc2 = "^1.5.0"
flask-oidc = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
downloadservice = { callable = "downloadservice:main" }